pl = ContainerPlotter();
%%
pl.default();
pl.plot( pup.only('lager'), 'images', {'doses'} ...
  , 'shape', [] ...
  , 'order_by', [] ...
  , 'add_ribbon', true ...
  , 'error_function', @std ...
  , 'y_lim', [0 5000] ...
  , 'full_screen', true ...
);
%%
pl.default();
pl.bar( look, 'images', 'doses', 'monkeys' ...
  , 'shape', [3 2] ...
  , 'order_by', {'saline', 'low', 'high'} ...
  , 'full_screen', true ...
);
