%{
    Define as many paramaters as you want in this file. Then call
    paraminclude(<filename>) to add the params struct to the function
%}


params = struct(...
    'calc','mean', ...
    'withinSession',0, ...
    'yLimits',[], ...
    'saveString', [], ...
    'yLabel',[], ...
    'xLabel',[], ...
    'xTickLabel',[], ...
    'title',[] ...
);

subfolder = 'plot';

folder = fullfile(pathfor('parameters'),subfolder);

save(fullfile(folder,'Params__plot.mat'),'params');

